language: node_js
node_js:
  - node
branches:
  only:
    - deploy
script:
  - npm i
  - npm run test

deploy:
  local_dir: dist
  provide: pages
  skip_cleanup: true
  github_token: $githubToken
  keep_history: true
  on:
    branch: deploy




